
= 项目介绍

== 使用说明

* runtest 中配置运行参数
* 运行 runtest
* https 调试：`playwright open --ignore-https-errors --viewport-size=1920,1080 https://192.168.1.104:9104/`

== 项目结构

理论上一个部位的退变、外伤、损伤合并外伤分别对应一个报告页面。

=== 元素和方法配置pages下

pages下，`add_report_base_page.py` 是结构化报告页面的基类，`add_report_kuan_tui_bian.py` 是具体的报告页面类，是髋退变对应的报告页面类。

==== 使用技巧

勾选checkbox，不能复用selenium的xpath定位，使用plaawright的录制定位方式如下：`self.data_guzhi_zengsheng = self.page.get_by_role("row", name="骨质增生 骨质增生，骨髓未见明显异常信号影").locator("span").nth(1)`

然后data设置不同的值，勾选不同的数据。

运行报告：`allure open ./report --host 192.168.1.18 --port 8080`或`python -m http.server 8080 --bind 192.168.1.18 -d report`

headless：`headless=True`

==== 调试

* 需要停止的地方写入 `page.pause()`，或者 `self.page.pause()`。
* Pycharm终端中操作
** 输入 `set PWDEBUG=1`，设置调试模式环境变量。
** `pytest -s -k test_add_report_kuan6` 运行测试用例 `test_add_report_kuan6`。
* 自动启动浏览器和调试工具
* 调试工具点击 `Resume` 按钮，程序继续运行到pause处。
* 调试工具点击 `Step Over` 按钮，程序运行到下一行，一步一步进行操作。

==== 运行

将admin设置为1，打开图集列表
admin用户需要时普通模式，否则需要新建用户xurj，密码123456，模式为普通。