name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run your tests on default base_url
      run: pytest --tracing=retain-on-failure
    - name: Run your tests on ssl base_url
      run: pytest --tracing=retain-on-failure --base-url=https://fast.huacai.one
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-traces_and_results
        path: |
          allure-results/
          trace.zip